project:
  type: website
  output-dir: docs

project-base-url: /Portfolio/

website:

  title: "Portfolio: Joseph Hook"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



