project:
  type: website

output-dir: docs

project-base-url: /Portfolio/

website:

  title: "Portfolio: Joseph Hook"
  navbar:
    left:
      - href: index.html
        text: Home

      - href: about.html
        text: About

      - href: blog.html
        text: Project Blog
      
      - href: education.html
        text: Education 
      
      - href: technical_skills.html
        text: Technical Skills
      
      - href: projects.html
        text: Projects

      - href: resume.html
        text: Resume

      - href: contact.html
        text: Contact Information

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



