project:
  type: website

output-dir: docs

project-base-url: /Portfolio/

website:

  title: "Portfolio: Joseph Hook"
  navbar:
    left:
      - href: src/index.qmd
        text: Home

      - href: src/about.qmd
        text: About

      - href: src/blog.qmd
        text: Project Blog
      
      - href: src/education.qmd
        text: Education 
      
      - href: src/technical_skills.qmd
        text: Technical Skills
      
      - href: src/projects.qmd
        text: Projects

      - href: src/resume.qmd
        text: Resume

      - href: src/contact.qmd
        text: Contact Information

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



